// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

import (
	"database/sql"
	"time"
)

type Notification struct {
	ID            int64
	ReminderID    sql.NullInt64
	Body          string
	CreationDate  time.Time
	DismissalDate sql.NullTime
}

type Reminder struct {
	ID            int64
	Interval      string
	CreationDate  time.Time
	Body          string
	DismissalDate sql.NullTime
	LastFired     sql.NullTime
}
